name: sw

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - name: stage1
      run: tools/bootstrap/win.bat
    - name: stage2
      run: |
        .\sw.exe build
    - uses: actions/upload-artifact@v3
      with:
        name: sw-${{github.job}}
        path: "*.exe"
        
  linux:
    runs-on: ubuntu-22.04
    container:
      image: fedora:37
      options: --security-opt seccomp=unconfined
    steps:
    - uses: actions/checkout@v3
    - name: prepare
      run: |
        sudo dnf -y install gcc g++ fmt-devel
    - name: stage1
      run: tools/bootstrap/linux.sh
    - name: stage2
      run: |
        ./sw build
    - uses: actions/upload-artifact@v3
      with:
        name: sw-${{github.job}}
        path: sw

  macos:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - run: sudo xcode-select --switch /Library/Developer/CommandLineTools
    - run: brew install fmt
    - name: stage1
      run: tools/bootstrap/macos.sh
    - name: stage2
      run: |
        export PATH="/usr/local/opt/gcc/bin:$PATH"
        ./sw build
    - uses: actions/upload-artifact@v3
      with:
        name: sw-${{github.job}}
        path: sw
