name: sw

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - name: stage1
      run: |
        cl -nologo -std:c++latest -EHsc src/*.cpp -link -OUT:sw.exe
    - name: stage2
      run: |
        .\sw.exe build
    - uses: actions/upload-artifact@v3
      with:
        name: sw-${{github.job}}
        path: "*.exe"

  ubuntu:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: prepare
      run: |
        sudo apt-get install -y gcc g++ fmt-devel
    - name: stage1
      run: |
        g++ -std=c++2b src/*.cpp -o sw
    - name: stage2
      run: |
        ./sw build
    - uses: actions/upload-artifact@v3
      with:
        name: sw-${{github.job}}
        path: sw
        
  fedora:
    runs-on: ubuntu-22.04
    container:
      image: fedora:37
      options: --security-opt seccomp=unconfined
    steps:
    - uses: actions/checkout@v3
    - name: prepare
      run: |
        sudo dnf -y install gcc g++ fmt-devel
    - name: stage1
      run: |
        g++ -std=c++2b src/*.cpp -o sw
    - name: stage2
      run: |
        ./sw build
    - uses: actions/upload-artifact@v3
      with:
        name: sw-${{github.job}}
        path: sw

  macos:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - run: sudo xcode-select --switch /Library/Developer/CommandLineTools
    - run: brew install fmt
    - name: stage1
      run: |
        export PATH="/usr/local/opt/gcc/bin:$PATH"
        g++-12 -std=c++2b src/*.cpp -I/usr/local/opt/fmt/include -o sw
    - name: stage2
      run: |
        export PATH="/usr/local/opt/gcc/bin:$PATH"
        ./sw build
    - uses: actions/upload-artifact@v3
      with:
        name: sw-${{github.job}}
        path: sw
