name: sw

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - run: cl -nologo -std:c++latest -EHsc src/*.cpp -link -OUT:sw.exe
    - run: .\sw.exe build
    - uses: actions/upload-artifact@v3
      with:
        name: sw
        path: "*.exe"
        
  mingw64:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MSYS
    - shell: msys2 {0}
      run: |
        pacman --noconfirm -S mingw-w64-x86_64-fmt
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
    - run: g++ --version
    - run: g++ -std=c++2b src/*.cpp -o sw
    - run: ./sw build
    - uses: actions/upload-artifact@v3
      with:
        name: sw
        path: sw

  linux:
    runs-on: ubuntu-22.04
    container:
      image: fedora:37
      options: --security-opt seccomp=unconfined
    steps:
    - uses: actions/checkout@v3
    - name: prepare
      run: |
        sudo dnf -y install gcc g++ fmt-devel
    - run: g++ -std=c++2b src/*.cpp -o sw
    - run: ./sw build
    - uses: actions/upload-artifact@v3
      with:
        name: sw
        path: sw

  macos:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: |
        export PATH="/usr/local/opt/gcc/bin:$PATH"
        g++-12 -std=c++2b src/*.cpp -o sw
    - run: ./sw build
    - uses: actions/upload-artifact@v3
      with:
        name: sw
        path: sw
