name: sw

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-2022    
    steps:
    - uses: actions/checkout@v3
    - uses: ilammy/msvc-dev-cmd@v1
    - run: cl -nologo -std:c++latest -EHsc src/*.cpp advapi32.lib ole32.lib OleAut32.lib -link -OUT:sw.exe
    - uses: actions/upload-artifact@v3
      with:
        name: sw
        path: "*.exe"

  linux:
    runs-on: ubuntu-20.04
    container: fedora:36
    steps:
    - uses: actions/checkout@v3
    - name: prepare
      run: |
        sudo dnf -y update
        sudo dnf -y install gcc g++ fmt
    - run: ls /usr/include
    - run: ls /usr/include/fmt
    - run: ls /usr/local/include
    - run: g++ -std=c++2b src/*.cpp -o sw
    - uses: actions/upload-artifact@v3
      with:
        name: sw
        path: sw
                
  macos:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: install
      run: brew install fmt
    - name: build
      run: |
        export PATH="/usr/local/opt/gcc/bin:$PATH"
        g++-12 -std=c++2b src/*.cpp -o sw -I/usr/local/include
    - uses: actions/upload-artifact@v3
      with:
        name: sw
        path: sw
